package br.com.hospital.pojo;

// Generated 08/02/2015 10:48:05 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Agendamento generated by hbm2java
 */
@Entity
@Table(name = "agendamento")
public class Agendamento implements java.io.Serializable {

	private static final long serialVersionUID = 2104680360321002088L;
	private Integer agenIdAgendamento;
	private Atendente atendente;
	private Medico medico;
	private Situacao situacao;
	private Paciente paciente;
	private EstadoPaciente estadoPaciente;
	private String agenTxAnamnese;
	private Date agenDtAgendamento;
	private Integer agenIdAtendente;
	private Date agenDtEspera;

	public Agendamento() {
	}

	public Agendamento(Atendente atendente, Medico medico, Situacao situacao,
			Paciente paciente, EstadoPaciente estadoPaciente) {
		this.atendente = atendente;
		this.medico = medico;
		this.situacao = situacao;
		this.paciente = paciente;
		this.estadoPaciente = estadoPaciente;
	}

	public Agendamento(Atendente atendente, Medico medico, Situacao situacao,
			Paciente paciente, EstadoPaciente estadoPaciente,
			String agenTxAnamnese, Date agenDtAgendamento,
			Integer agenIdAtendente, Date agenDtEspera) {
		this.atendente = atendente;
		this.medico = medico;
		this.situacao = situacao;
		this.paciente = paciente;
		this.estadoPaciente = estadoPaciente;
		this.agenTxAnamnese = agenTxAnamnese;
		this.agenDtAgendamento = agenDtAgendamento;
		this.agenIdAtendente = agenIdAtendente;
		this.agenDtEspera = agenDtEspera;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "AGEN_ID_AGENDAMENTO", unique = true, nullable = false)
	public Integer getAgenIdAgendamento() {
		return this.agenIdAgendamento;
	}

	public void setAgenIdAgendamento(Integer agenIdAgendamento) {
		this.agenIdAgendamento = agenIdAgendamento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ATEN_ID_PESSOA", nullable = false)
	public Atendente getAtendente() {
		return this.atendente;
	}

	public void setAtendente(Atendente atendente) {
		this.atendente = atendente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MEDI_ID_PESSOA", nullable = false)
	public Medico getMedico() {
		return this.medico;
	}

	public void setMedico(Medico medico) {
		this.medico = medico;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SITU_ID_SITUACAO", nullable = false)
	public Situacao getSituacao() {
		return this.situacao;
	}

	public void setSituacao(Situacao situacao) {
		this.situacao = situacao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PACI_ID_PESSOA", nullable = false)
	public Paciente getPaciente() {
		return this.paciente;
	}

	public void setPaciente(Paciente paciente) {
		this.paciente = paciente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ESPA_ID_ESTADO", nullable = false)
	public EstadoPaciente getEstadoPaciente() {
		return this.estadoPaciente;
	}

	public void setEstadoPaciente(EstadoPaciente estadoPaciente) {
		this.estadoPaciente = estadoPaciente;
	}

	@Column(name = "AGEN_TX_ANAMNESE", length = 1000)
	public String getAgenTxAnamnese() {
		return this.agenTxAnamnese;
	}

	public void setAgenTxAnamnese(String agenTxAnamnese) {
		this.agenTxAnamnese = agenTxAnamnese;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "AGEN_DT_AGENDAMENTO", length = 10)
	public Date getAgenDtAgendamento() {
		return this.agenDtAgendamento;
	}

	public void setAgenDtAgendamento(Date agenDtAgendamento) {
		this.agenDtAgendamento = agenDtAgendamento;
	}

	@Column(name = "AGEN_ID_ATENDENTE")
	public Integer getAgenIdAtendente() {
		return this.agenIdAtendente;
	}

	public void setAgenIdAtendente(Integer agenIdAtendente) {
		this.agenIdAtendente = agenIdAtendente;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "AGEN_DT_ESPERA", length = 8)
	public Date getAgenDtEspera() {
		return this.agenDtEspera;
	}

	public void setAgenDtEspera(Date agenDtEspera) {
		this.agenDtEspera = agenDtEspera;
	}

}
