package br.com.hospital.pojo;

// Generated 08/02/2015 10:48:05 by Hibernate Tools 4.0.0

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Atendente generated by hbm2java
 */
@Entity
@Table(name = "atendente")
public class Atendente implements java.io.Serializable {

	private static final long serialVersionUID = 180854448495986451L;
	private int atenIdPessoa;
	private Pessoa pessoa;
	private String atenTxSenha;
	private List<Agendamento> agendamentos = new ArrayList<Agendamento>();

	public Atendente() {
	}

	public Atendente(Pessoa pessoa, String atenTxSenha) {
		this.pessoa = pessoa;
		this.atenTxSenha = atenTxSenha;
	}

	public Atendente(Pessoa pessoa, String atenTxSenha, List<Agendamento> agendamentos) {
		this.pessoa = pessoa;
		this.atenTxSenha = atenTxSenha;
		this.agendamentos = agendamentos;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "pessoa"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "ATEN_ID_PESSOA", unique = true, nullable = false)
	public int getAtenIdPessoa() {
		return this.atenIdPessoa;
	}

	public void setAtenIdPessoa(int atenIdPessoa) {
		this.atenIdPessoa = atenIdPessoa;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Pessoa getPessoa() {
		return this.pessoa;
	}

	public void setPessoa(Pessoa pessoa) {
		this.pessoa = pessoa;
	}

	@Column(name = "ATEN_TX_SENHA", nullable = false, length = 100)
	public String getAtenTxSenha() {
		return this.atenTxSenha;
	}

	public void setAtenTxSenha(String atenTxSenha) {
		this.atenTxSenha = atenTxSenha;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "atendente")
	public List<Agendamento> getAgendamentos() {
		return this.agendamentos;
	}

	public void setAgendamentos(List<Agendamento> agendamentos) {
		this.agendamentos = agendamentos;
	}

}
