package br.com.hospital.pojo;

// Generated 08/02/2015 10:48:05 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Especialidade generated by hbm2java
 */
@Entity
@Table(name = "especialidade")
public class Especialidade implements java.io.Serializable {

	private static final long serialVersionUID = 8300769326198704562L;
	private Integer espeIdEspecialidade;
	private String espeNmEspecialidade;
	private List<Medico> medicos = new ArrayList<Medico>();

	public Especialidade() {
	}

	public Especialidade(String espeNmEspecialidade, List<Medico> medicos) {
		this.espeNmEspecialidade = espeNmEspecialidade;
		this.medicos = medicos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ESPE_ID_ESPECIALIDADE", unique = true, nullable = false)
	public Integer getEspeIdEspecialidade() {
		return this.espeIdEspecialidade;
	}

	public void setEspeIdEspecialidade(Integer espeIdEspecialidade) {
		this.espeIdEspecialidade = espeIdEspecialidade;
	}

	@Column(name = "ESPE_NM_ESPECIALIDADE", length = 100)
	public String getEspeNmEspecialidade() {
		return this.espeNmEspecialidade;
	}

	public void setEspeNmEspecialidade(String espeNmEspecialidade) {
		this.espeNmEspecialidade = espeNmEspecialidade;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "especialidade")
	public List<Medico> getMedicos() {
		return this.medicos;
	}

	public void setMedicos(List<Medico> medicos) {
		this.medicos = medicos;
	}

}
