package br.com.hospital.pojo;

// Generated 08/02/2015 10:48:05 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EstadoPaciente generated by hbm2java
 */
@Entity
@Table(name = "estado_paciente")
public class EstadoPaciente implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8269866992165244808L;
	private Integer espaIdEstado;
	private String espaNmEstado;
	private List<Agendamento> agendamentos = new ArrayList<Agendamento>();

	public EstadoPaciente() {
	}

	public EstadoPaciente(String espaNmEstado, List<Agendamento> agendamentos) {
		this.espaNmEstado = espaNmEstado;
		this.agendamentos = agendamentos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ESPA_ID_ESTADO", unique = true, nullable = false)
	public Integer getEspaIdEstado() {
		return this.espaIdEstado;
	}

	public void setEspaIdEstado(Integer espaIdEstado) {
		this.espaIdEstado = espaIdEstado;
	}

	@Column(name = "ESPA_NM_ESTADO", length = 100)
	public String getEspaNmEstado() {
		return this.espaNmEstado;
	}

	public void setEspaNmEstado(String espaNmEstado) {
		this.espaNmEstado = espaNmEstado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estadoPaciente")
	public List<Agendamento> getAgendamentos() {
		return this.agendamentos;
	}

	public void setAgendamentos(List<Agendamento> agendamentos) {
		this.agendamentos = agendamentos;
	}

}
