package br.com.hospital.pojo;

// Generated 08/02/2015 10:48:05 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Municipio generated by hbm2java
 */
@Entity
@Table(name = "municipio")
public class Municipio implements java.io.Serializable {

	private static final long serialVersionUID = 1279996870333377319L;
	private Integer muniIdMunicipio;
	private UnidadeFederativa unidadeFederativa;
	private String muniNmMunicipio;
	private List<Pessoa> pessoas = new ArrayList<Pessoa>();

	public Municipio() {
	}

	public Municipio(UnidadeFederativa unidadeFederativa) {
		this.unidadeFederativa = unidadeFederativa;
	}

	public Municipio(UnidadeFederativa unidadeFederativa,
			String muniNmMunicipio, List<Pessoa> pessoas) {
		this.unidadeFederativa = unidadeFederativa;
		this.muniNmMunicipio = muniNmMunicipio;
		this.pessoas = pessoas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "MUNI_ID_MUNICIPIO", unique = true, nullable = false)
	public Integer getMuniIdMunicipio() {
		return this.muniIdMunicipio;
	}

	public void setMuniIdMunicipio(Integer muniIdMunicipio) {
		this.muniIdMunicipio = muniIdMunicipio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UNFE_ID_UNIDADE", nullable = false)
	public UnidadeFederativa getUnidadeFederativa() {
		return this.unidadeFederativa;
	}

	public void setUnidadeFederativa(UnidadeFederativa unidadeFederativa) {
		this.unidadeFederativa = unidadeFederativa;
	}

	@Column(name = "MUNI_NM_MUNICIPIO", length = 100)
	public String getMuniNmMunicipio() {
		return this.muniNmMunicipio;
	}

	public void setMuniNmMunicipio(String muniNmMunicipio) {
		this.muniNmMunicipio = muniNmMunicipio;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "municipio")
	public List<Pessoa> getPessoas() {
		return this.pessoas;
	}

	public void setPessoas(List<Pessoa> pessoas) {
		this.pessoas = pessoas;
	}

}
