package br.com.hospital.pojo;

// Generated 08/02/2015 10:48:05 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Pessoa generated by hbm2java
 */
@Entity
@Table(name = "pessoa")
public class Pessoa implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4986111048493573627L;
	private Integer pessIdPessoa;
	private Municipio municipio;
	private TipoAcesso tipoAcesso;
	private String pessNmNome;
	private String pessNrCpf;
	private String pessTxLogradouro;
	private String pessNrNumero;
	private String pessTxCep;
	private String pessTxBairro;
	private String pessTxComplemento;
	private String pessTxEmail;
	private String pessNrTelefone;
	private String pessNrCelular;
	private String pessTxSenha;
	private Medico medico;
	private Atendente atendente;
	private Paciente paciente;
	private PlanoDeSaude planoDeSaude;

	public Pessoa() {
	}

	public Pessoa(Municipio municipio, TipoAcesso tipoAcesso) {
		this.municipio = municipio;
		this.tipoAcesso = tipoAcesso;
	}

	public Pessoa(Municipio municipio, TipoAcesso tipoAcesso,
			String pessNmNome, String pessNrCpf, String pessTxLogradouro,
			String pessNrNumero, String pessTxCep, String pessTxBairro,
			String pessTxComplemento, String pessTxEmail,
			String pessNrTelefone, String pessNrCelular, String pessTxSenha,
			Medico medico, Atendente atendente, Paciente paciente,
			PlanoDeSaude planoDeSaude) {
		this.municipio = municipio;
		this.tipoAcesso = tipoAcesso;
		this.pessNmNome = pessNmNome;
		this.pessNrCpf = pessNrCpf;
		this.pessTxLogradouro = pessTxLogradouro;
		this.pessNrNumero = pessNrNumero;
		this.pessTxCep = pessTxCep;
		this.pessTxBairro = pessTxBairro;
		this.pessTxComplemento = pessTxComplemento;
		this.pessTxEmail = pessTxEmail;
		this.pessNrTelefone = pessNrTelefone;
		this.pessNrCelular = pessNrCelular;
		this.pessTxSenha = pessTxSenha;
		this.medico = medico;
		this.atendente = atendente;
		this.paciente = paciente;
		this.planoDeSaude = planoDeSaude;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PESS_ID_PESSOA", unique = true, nullable = false)
	public Integer getPessIdPessoa() {
		return this.pessIdPessoa;
	}

	public void setPessIdPessoa(Integer pessIdPessoa) {
		this.pessIdPessoa = pessIdPessoa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MUNI_ID_MUNICIPIO", nullable = false)
	public Municipio getMunicipio() {
		return this.municipio;
	}

	public void setMunicipio(Municipio municipio) {
		this.municipio = municipio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TIAC_ID_TIPO", nullable = false)
	public TipoAcesso getTipoAcesso() {
		return this.tipoAcesso;
	}

	public void setTipoAcesso(TipoAcesso tipoAcesso) {
		this.tipoAcesso = tipoAcesso;
	}

	@Column(name = "PESS_NM_NOME", length = 100)
	public String getPessNmNome() {
		return this.pessNmNome;
	}

	public void setPessNmNome(String pessNmNome) {
		this.pessNmNome = pessNmNome;
	}

	@Column(name = "PESS_NR_CPF", length = 20)
	public String getPessNrCpf() {
		return this.pessNrCpf;
	}

	public void setPessNrCpf(String pessNrCpf) {
		this.pessNrCpf = pessNrCpf;
	}

	@Column(name = "PESS_TX_LOGRADOURO", length = 100)
	public String getPessTxLogradouro() {
		return this.pessTxLogradouro;
	}

	public void setPessTxLogradouro(String pessTxLogradouro) {
		this.pessTxLogradouro = pessTxLogradouro;
	}

	@Column(name = "PESS_NR_NUMERO", length = 10)
	public String getPessNrNumero() {
		return this.pessNrNumero;
	}

	public void setPessNrNumero(String pessNrNumero) {
		this.pessNrNumero = pessNrNumero;
	}

	@Column(name = "PESS_TX_CEP", length = 20)
	public String getPessTxCep() {
		return this.pessTxCep;
	}

	public void setPessTxCep(String pessTxCep) {
		this.pessTxCep = pessTxCep;
	}

	@Column(name = "PESS_TX_BAIRRO", length = 100)
	public String getPessTxBairro() {
		return this.pessTxBairro;
	}

	public void setPessTxBairro(String pessTxBairro) {
		this.pessTxBairro = pessTxBairro;
	}

	@Column(name = "PESS_TX_COMPLEMENTO", length = 100)
	public String getPessTxComplemento() {
		return this.pessTxComplemento;
	}

	public void setPessTxComplemento(String pessTxComplemento) {
		this.pessTxComplemento = pessTxComplemento;
	}

	@Column(name = "PESS_TX_EMAIL", length = 100)
	public String getPessTxEmail() {
		return this.pessTxEmail;
	}

	public void setPessTxEmail(String pessTxEmail) {
		this.pessTxEmail = pessTxEmail;
	}

	@Column(name = "PESS_NR_TELEFONE", length = 20)
	public String getPessNrTelefone() {
		return this.pessNrTelefone;
	}

	public void setPessNrTelefone(String pessNrTelefone) {
		this.pessNrTelefone = pessNrTelefone;
	}

	@Column(name = "PESS_NR_CELULAR", length = 20)
	public String getPessNrCelular() {
		return this.pessNrCelular;
	}

	public void setPessNrCelular(String pessNrCelular) {
		this.pessNrCelular = pessNrCelular;
	}

	@Column(name = "PESS_TX_SENHA", length = 100)
	public String getPessTxSenha() {
		return this.pessTxSenha;
	}

	public void setPessTxSenha(String pessTxSenha) {
		this.pessTxSenha = pessTxSenha;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "pessoa")
	public Medico getMedico() {
		return this.medico;
	}

	public void setMedico(Medico medico) {
		this.medico = medico;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "pessoa")
	public Atendente getAtendente() {
		return this.atendente;
	}

	public void setAtendente(Atendente atendente) {
		this.atendente = atendente;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "pessoa")
	public Paciente getPaciente() {
		return this.paciente;
	}

	public void setPaciente(Paciente paciente) {
		this.paciente = paciente;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "pessoa")
	public PlanoDeSaude getPlanoDeSaude() {
		return this.planoDeSaude;
	}

	public void setPlanoDeSaude(PlanoDeSaude planoDeSaude) {
		this.planoDeSaude = planoDeSaude;
	}

}
