package br.com.hospital.pojo;

// Generated 08/02/2015 10:48:05 by Hibernate Tools 4.0.0

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * PlanoDeSaude generated by hbm2java
 */
@Entity
@Table(name = "plano_de_saude")
public class PlanoDeSaude implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4916218159142986649L;
	private int pldsIdPessoa;
	private Pessoa pessoa;
	private String pldsNrCnpj;
	private String pldsNrFax;
	private List<Paciente> pacientes = new ArrayList<Paciente>();

	public PlanoDeSaude() {
	}

	public PlanoDeSaude(Pessoa pessoa, String pldsNrCnpj, String pldsNrFax) {
		this.pessoa = pessoa;
		this.pldsNrCnpj = pldsNrCnpj;
		this.pldsNrFax = pldsNrFax;
	}

	public PlanoDeSaude(Pessoa pessoa, String pldsNrCnpj, String pldsNrFax,
			List<Paciente> pacientes) {
		this.pessoa = pessoa;
		this.pldsNrCnpj = pldsNrCnpj;
		this.pldsNrFax = pldsNrFax;
		this.pacientes = pacientes;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "pessoa"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "PLDS_ID_PESSOA", unique = true, nullable = false)
	public int getPldsIdPessoa() {
		return this.pldsIdPessoa;
	}

	public void setPldsIdPessoa(int pldsIdPessoa) {
		this.pldsIdPessoa = pldsIdPessoa;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Pessoa getPessoa() {
		return this.pessoa;
	}

	public void setPessoa(Pessoa pessoa) {
		this.pessoa = pessoa;
	}

	@Column(name = "PLDS_NR_CNPJ", nullable = false, length = 100)
	public String getPldsNrCnpj() {
		return this.pldsNrCnpj;
	}

	public void setPldsNrCnpj(String pldsNrCnpj) {
		this.pldsNrCnpj = pldsNrCnpj;
	}

	@Column(name = "PLDS_NR_FAX", nullable = false, length = 20)
	public String getPldsNrFax() {
		return this.pldsNrFax;
	}

	public void setPldsNrFax(String pldsNrFax) {
		this.pldsNrFax = pldsNrFax;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "planoDeSaude")
	public List<Paciente> getPacientes() {
		return this.pacientes;
	}

	public void setPacientes(List<Paciente> pacientes) {
		this.pacientes = pacientes;
	}

}
