package br.com.hospital.pojo;

// Generated 08/02/2015 10:48:05 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Situacao generated by hbm2java
 */
@Entity
@Table(name = "situacao")
public class Situacao implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6240253544988257466L;
	private Integer situIdSituacao;
	private String situNmSituacao;
	private List<Agendamento> agendamentos = new ArrayList<Agendamento>();

	public Situacao() {
	}

	public Situacao(String situNmSituacao, List<Agendamento> agendamentos) {
		this.situNmSituacao = situNmSituacao;
		this.agendamentos = agendamentos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "SITU_ID_SITUACAO", unique = true, nullable = false)
	public Integer getSituIdSituacao() {
		return this.situIdSituacao;
	}

	public void setSituIdSituacao(Integer situIdSituacao) {
		this.situIdSituacao = situIdSituacao;
	}

	@Column(name = "SITU_NM_SITUACAO", length = 100)
	public String getSituNmSituacao() {
		return this.situNmSituacao;
	}

	public void setSituNmSituacao(String situNmSituacao) {
		this.situNmSituacao = situNmSituacao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "situacao")
	public List<Agendamento> getAgendamentos() {
		return this.agendamentos;
	}

	public void setAgendamentos(List<Agendamento> agendamentos) {
		this.agendamentos = agendamentos;
	}

}
