package br.com.hospital.pojo;

// Generated 08/02/2015 10:48:05 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoAcesso generated by hbm2java
 */
@Entity
@Table(name = "tipo_acesso", catalog = "hospital")
public class TipoAcesso implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -313167273313713222L;
	private Integer tiacIdTipo;
	private String tiacTxTipo;
	private String tiacNmTipo;
	private List<Pessoa> pessoas = new ArrayList<Pessoa>();

	public TipoAcesso() {
	}

	public TipoAcesso(String tiacTxTipo, String tiacNmTipo, List<Pessoa> pessoas) {
		this.tiacTxTipo = tiacTxTipo;
		this.tiacNmTipo = tiacNmTipo;
		this.pessoas = pessoas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "TIAC_ID_TIPO", unique = true, nullable = false)
	public Integer getTiacIdTipo() {
		return this.tiacIdTipo;
	}

	public void setTiacIdTipo(Integer tiacIdTipo) {
		this.tiacIdTipo = tiacIdTipo;
	}

	@Column(name = "TIAC_TX_TIPO", length = 100)
	public String getTiacTxTipo() {
		return this.tiacTxTipo;
	}

	public void setTiacTxTipo(String tiacTxTipo) {
		this.tiacTxTipo = tiacTxTipo;
	}

	@Column(name = "TIAC_NM_TIPO", length = 100)
	public String getTiacNmTipo() {
		return this.tiacNmTipo;
	}

	public void setTiacNmTipo(String tiacNmTipo) {
		this.tiacNmTipo = tiacNmTipo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoAcesso")
	public List<Pessoa> getPessoas() {
		return this.pessoas;
	}

	public void setPessoas(List<Pessoa> pessoas) {
		this.pessoas = pessoas;
	}

}
