package br.com.hospital.pojo;

// Generated 08/02/2015 10:48:05 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoPlanoSaude generated by hbm2java
 */
@Entity
@Table(name = "tipo_plano_saude")
public class TipoPlanoSaude implements java.io.Serializable {

	private static final long serialVersionUID = -7460357299649877468L;
	private Integer tipsIdTipo;
	private String tipsNmNome;
	private List<Paciente> pacientes = new ArrayList<Paciente>();

	public TipoPlanoSaude() {
	}

	public TipoPlanoSaude(String tipsNmNome, List<Paciente> pacientes) {
		this.tipsNmNome = tipsNmNome;
		this.pacientes = pacientes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "TIPS_ID_TIPO", unique = true, nullable = false)
	public Integer getTipsIdTipo() {
		return this.tipsIdTipo;
	}

	public void setTipsIdTipo(Integer tipsIdTipo) {
		this.tipsIdTipo = tipsIdTipo;
	}

	@Column(name = "TIPS_NM_NOME", length = 100)
	public String getTipsNmNome() {
		return this.tipsNmNome;
	}

	public void setTipsNmNome(String tipsNmNome) {
		this.tipsNmNome = tipsNmNome;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoPlanoSaude")
	public List<Paciente> getPacientes() {
		return this.pacientes;
	}

	public void setPacientes(List<Paciente> pacientes) {
		this.pacientes = pacientes;
	}

}
