package br.com.hospital.pojo;

// Generated 08/02/2015 10:48:05 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UnidadeFederativa generated by hbm2java
 */
@Entity
@Table(name = "unidade_federativa")
public class UnidadeFederativa implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 583954715092828797L;
	private Integer unfeIdUnidade;
	private String unfeNmUnidade;
	private List<Municipio> municipios = new ArrayList<Municipio>();

	public UnidadeFederativa() {
	}

	public UnidadeFederativa(String unfeNmUnidade, List<Municipio> municipios) {
		this.unfeNmUnidade = unfeNmUnidade;
		this.municipios = municipios;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "UNFE_ID_UNIDADE", unique = true, nullable = false)
	public Integer getUnfeIdUnidade() {
		return this.unfeIdUnidade;
	}

	public void setUnfeIdUnidade(Integer unfeIdUnidade) {
		this.unfeIdUnidade = unfeIdUnidade;
	}

	@Column(name = "UNFE_NM_UNIDADE", length = 100)
	public String getUnfeNmUnidade() {
		return this.unfeNmUnidade;
	}

	public void setUnfeNmUnidade(String unfeNmUnidade) {
		this.unfeNmUnidade = unfeNmUnidade;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "unidadeFederativa")
	public List<Municipio> getMunicipios() {
		return this.municipios;
	}

	public void setMunicipios(List<Municipio> municipios) {
		this.municipios = municipios;
	}

}
