package br.com.hospital.pojo;

// Generated 03/12/2014 21:22:56 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EstadoPaciente generated by hbm2java
 */
@Entity
@Table(name = "estado_paciente", catalog = "hospital")
public class EstadoPaciente implements java.io.Serializable {

	private Integer espaIdEstado;
	private String espaNmEstado;

	public EstadoPaciente() {
	}

	public EstadoPaciente(String espaNmEstado) {
		this.espaNmEstado = espaNmEstado;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ESPA_ID_ESTADO", unique = true, nullable = false)
	public Integer getEspaIdEstado() {
		return this.espaIdEstado;
	}

	public void setEspaIdEstado(Integer espaIdEstado) {
		this.espaIdEstado = espaIdEstado;
	}

	@Column(name = "ESPA_NM_ESTADO", length = 100)
	public String getEspaNmEstado() {
		return this.espaNmEstado;
	}

	public void setEspaNmEstado(String espaNmEstado) {
		this.espaNmEstado = espaNmEstado;
	}

}
