package br.com.hospital.pojo;

// Generated 03/12/2014 21:22:56 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Situacao generated by hbm2java
 */
@Entity
@Table(name = "situacao", catalog = "hospital")
public class Situacao implements java.io.Serializable {

	private Integer situIdSituacao;
	private String situNmSituacao;

	public Situacao() {
	}

	public Situacao(String situNmSituacao) {
		this.situNmSituacao = situNmSituacao;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "SITU_ID_SITUACAO", unique = true, nullable = false)
	public Integer getSituIdSituacao() {
		return this.situIdSituacao;
	}

	public void setSituIdSituacao(Integer situIdSituacao) {
		this.situIdSituacao = situIdSituacao;
	}

	@Column(name = "SITU_NM_SITUACAO", length = 100)
	public String getSituNmSituacao() {
		return this.situNmSituacao;
	}

	public void setSituNmSituacao(String situNmSituacao) {
		this.situNmSituacao = situNmSituacao;
	}

}
