package br.com.hospital.pojo;

// Generated 03/12/2014 21:22:56 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TipoAcesso generated by hbm2java
 */
@Entity
@Table(name = "tipo_acesso", catalog = "hospital")
public class TipoAcesso implements java.io.Serializable {

	private Integer tiacIdTipo;
	private String tiacNmTipo;

	public TipoAcesso() {
	}

	public TipoAcesso(String tiacNmTipo) {
		this.tiacNmTipo = tiacNmTipo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "TIAC_ID_TIPO", unique = true, nullable = false)
	public Integer getTiacIdTipo() {
		return this.tiacIdTipo;
	}

	public void setTiacIdTipo(Integer tiacIdTipo) {
		this.tiacIdTipo = tiacIdTipo;
	}

	@Column(name = "TIAC_NM_TIPO", length = 100)
	public String getTiacNmTipo() {
		return this.tiacNmTipo;
	}

	public void setTiacNmTipo(String tiacNmTipo) {
		this.tiacNmTipo = tiacNmTipo;
	}

}
